#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
import os
import time
import dbus
import requests

from bs4 import BeautifulSoup
old_metadata = None


def get_metadata():
    session_bus = dbus.SessionBus()
    spotify_bus = session_bus.get_object("org.mpris.MediaPlayer2.spotify",
                                         "/org/mpris/MediaPlayer2")
    spotify_properties = dbus.Interface(spotify_bus,
                                        "org.freedesktop.DBus.Properties")
    return spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")


base_url = "http://api.genius.com"
headers = {
    'Authorization': 'Bearer dp7sB4-Li2skNwHMdBuXz2yQYKm2moTTW7aVLI1yLBxVnB479rf3HFDJbB9hoDe0'}
search_url = base_url + "/search"


def print_lyrics(lyric_lines):
    terminal_cols = os.popen('tput cols').read()
    title = '[\033[4m' + metadata['xesam:artist'][0].title() + '/' + \
        metadata['xesam:title'] + '\033[0m]'
    print title.center(int(terminal_cols) + 10)
    print '\033[1m',
    print '\n'.join([line.center(int(terminal_cols)) for line in lyric_lines])

    print '\033[0m'


while 1:

    metadata = get_metadata()

    if metadata != old_metadata:
        old_metadata = metadata

        data = {'q': str(metadata['xesam:title']) +
                ' ' + str(metadata['xesam:artist'][0])}
        try:
            
            genius = requests.get(search_url, params=data, headers=headers).json()
            lyrics_url = genius["response"]["hits"][0]["result"]['url']
            page = requests.get(lyrics_url)

            html = BeautifulSoup(page.content, "html.parser")
            lyrics_ = html.find("div", class_="lyrics").get_text()
         except Exception:
            print 'error occured when fetching lyric'
            continue
            
         
        terminal_cols = os.popen('tput cols').read()
        try:
            print_lyrics([''.join(x) for x in lyrics_.splitlines()])
        except Exception:
            print '[', metadata['xesam:artist'][0].title(), '/', metadata['xesam:title'], ']'
            print '----'

    time.sleep(3)
